version: '3'

services:
  web:
    build: 
      context: ..
      dockerfile: ./oserou/Dockerfile
    tty: true
    volumes:
      - ./:/workspace
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0ser0u
      MYSQL_DATABASE: oserou
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb_use_native_aio=0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=0ser0u

volumes:
    mysql_data: